### ISSUE TITLE
dockerize the application

### ISSUE THREAD

**Issue by houssemAmiri** [yebrahim/codersquare#22]

**Comment by yebrahim** [comment]
I'm not sure how much value we get by adding containers here, this is a pretty simple app with a single dependency on node.js. we don't even have a standalone database. :)

**Comment by yebrahim** [comment]
that said, I'm not strongly against using containers, just need to wait till the right time.

**Comment by houssemAmiri** [comment]
ok i will close the issue for now until we need to dockerize the app
