### ISSUE TITLE
Add comment handlers, implemented in both in-memory and sql datastores

### ISSUE THREAD

**Issue by yebrahim** [yebrahim/codersquare#3]
`createComment`
`listComments`
`deleteComment`

**Comment by MoustafaJazzar** [comment]
check my commit [here](https://github.com/MoustafaJazzar/codersquare/commit/52917f60aa239a2fc86dacb4b229af994570bb74)

- [x] `createComment` 
- [x] `listComments` 
- [x] `deleteComment`
