### ISSUE TITLE
add email input validation

### ISSUE THREAD

**Issue by hazemamy** [yebrahim/codersquare#35]
**ensure the user writes email correctly also name**
In the image below I'm trying to register and input doesn't make sense however it worked
 
![Screenshot (8)](https://user-images.githubusercontent.com/99791497/210954002-ed9a3ef6-a552-401f-bf25-91b79e5ed7a6.png)

**Comment by yebrahim** [comment]
Yep, we can add email validation through a library or a regex. Would you like to take a stab at this @hazhox?

**Comment by hazhox** [comment]
**I'll try to figure out a solution** don't expect much because I'm at an early stage of learning web development

**Comment by yebrahim** [comment]
Sure thing! I'd look up how to apply regular expressions here then, rather than just using a library to fix the problem. Happy to recite the code and offer feedback. :)

**Comment by Bardala** [comment]
I have tried to solve this issue
