### ISSUE TITLE
Add deletePostHandler, with both in-memory and sql implementations

### ISSUE THREAD

**Issue by yebrahim** [yebrahim/codersquare#9]

**Comment by mohamedsaleh1984** [comment]
hey Yasser,
Can you check my repo for deletePostHandler in-memory ?
Please have a look at the changes and let me know about the closed issues and I will do Pull Request when you confirm.
Thanks a lot for your contribution

**Comment by yebrahim** [comment]
Looks like you have a bunch of changes there, are you able to break them up to two or more PRs and send them over? If not let's just create a PR and I'll review all the changes at once. :)
